# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

resources:
 pipelines:
   - pipeline: 'buildContosoAir'
     source: cassiebueno.ContosoAir
     trigger:
      branches:
        include:
          - master

pool:
  vmImage: ubuntu-latest

steps:
- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'specific'
    project: 'cd0e5f44-4065-46c5-ade9-d7bab60bc887'
    definition: '2'
    specificBuildWithTriggering: true
    buildVersionToDownload: 'latest'
    targetPath: '$(Pipeline.Workspace)'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Free Trial(6beb00dc-071c-4d7e-bd3f-109b7ed4f2ad)'
    subscriptionId: '6beb00dc-071c-4d7e-bd3f-109b7ed4f2ad'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(resourcegroup)'
    location: 'Central US'
    templateLocation: 'Linked artifact'
    csmFile: '$(Pipeline.Workspace)/drop/azuredeploy.json'
    csmParametersFile: '$(Pipeline.Workspace)/drop/azuredeploy.parameters.json'
    overrideParameters: '-p_environment $(web_environment) -p_site_prefix $(web_prefix) -p_site_web_name $(web_site)'
    deploymentMode: 'Incremental'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Free Trial(1)(6beb00dc-071c-4d7e-bd3f-109b7ed4f2ad)'
    appType: 'webApp'
    WebAppName: '$(web_prefix)-$(web_site)-$(web_environment)'
    packageForLinux: '$(Pipeline.Workspace)/**/*.zip'
